#!/usr/bin/tcsh
while 1
  while 1
    echo -n "\nEnter your choice: "
    set ch = $<
    if( $ch =~ [a-h][1-6] ) break
    echo "Invalid choice. Please try again."
  end
  set x = `echo $ch | sed 'y/abcdefgh/12345678/;s/\([0-9]\)\([0-9]\)/\1 + \2 * 8 - 8/g' | xargs expr`
  ( expr $x != $1 && expr 1 + `cat memboard | sed -n "$x s/[A-X]/1/p;$x s/[_]/A/p"` ) >& /dev/null && exit $x
  echo "That place is already revealed. Please try again."
end
