#!/usr/bin/tcsh
while 1
  while 1
    echo -n "\nEnter your choice: "
    set ch = $<
    echo $ch | grep -o -e . | grep -o "[a-h]" | grep -q "[a-z]" && \
    echo $ch | grep -o -e . | grep -o "[1-6]" | grep -q "[0-9]" && break
    echo "Invalid choice. Please try again."
  end
  expr `echo $ch | grep -o -e . | sort | tr "\n[a-h]" "\+[1-8]" | grep -o -e . | tr '\n'  ' ' | xargs echo 8 \\\*` -8 > cau
  set x = `cat cau`
  if(x$1 != x$x || x$1 == x0) cat memboard | tr ',' '\n' | grep -n "[A-X]" | grep -q -w $x && exit $x
  echo "That place is already revealed. Please try again."
end
