#!/bin/bash
echo ABCDEFGHIJKLMNOPQRSTUVWX | grep -o -n "[A-X]" - | cut -c 2- | tee letters | tr '[A-Z]' '[a-z]' >> letters
#!/usr/bin/tcsh
sort -R letters | tr '[a-z]:\n' '[A-Z] ,' > memboard
set posx = 0
set posy = 0
set moves = 0
while(1)
  ./displayboard posx posy $1
  if($status == 1)then
    cat memboard | tr '' > tmpfile

