#!/bin/bash
echo ABCDEFGHIJKLMNOPQRSTUVWX | grep -o -n "[A-X]" - | cut -c 2- | tee letters | tr '[A-Z]' '[a-z]' >> letters
#!/usr/bin/tcsh
sort -R letters | tr '[a-z]:\n' '[A-Z] ,' > memboard
set posx = 0
set posy = 0
set moves = 0
while 1
  ./displayboard posx posy $1
  if($status == 0)then
    cat memboard | tr `head -1 tmpfile3| tr -d "[0-9] \t"` _ > tmpfile
    mv tmpfile memgame
    grep -v "[A-Z]" letters && echo a\\nb && exit
  endif
  ./getchoice 0
  $posy = $status
  ./displayboard posx 0 $1
  ./getchoice posy
  $posx = $status
  @ moves++
end
